version: "{build}"
image: Visual Studio 2017
environment:
  PYTHON: "C:\\Python36-x64"
  PYTHON_VERSION: 3.6
  PYTHON_ARCH: 64
build_script:
- cmd: >-
    python --version

    echo "environment: PYTHON=%PYTHON%"

    python -m unittest discover --verbose
